<header class="zm-header">
    <div class="zm-menu">
        <div class="zm-menu-item">
            <a href="<?php echo $this->url->get();?>">Index</a>
        </div>
        <div class="zm-menu-item">
            <a href="<?php echo $this->url->get('register');?>">Register</a>
        </div>
        <div class="zm-menu-item">
            <a href="<?php echo $this->url->get('login');?>">Login</a>
        </div>
    </div>
</header>