build:
  nodes:
    zemit:
      root_path: './'
      services:
        mysql: latest
        redis: 6
      resources:
        cpus: 4
      environment:
        timezone: 'America/New_York'
        hosts:
          core.zemit.local: 127.0.0.1
        php:
          version: 8.3.
          pecl_extensions:
            - redis
            - memcached
            - apcu
            - swoole
            - phalcon-5.9.3
          ini:
            memory_limit: -1
      dependencies:
        before:
          - composer self-update
        after:
          - composer update --no-interaction --prefer-dist
      tests:
        stop_on_failure: false
        override:
          - command: php-scrutinizer-run --enable-security-analysis
      cache:
        disabled: false
        directories:
          - ~/.composer
          - vendor/
checks:
  php: true
filter:
  excluded_paths:
    - 'tests/' # test suite
    - 'resources/' # other resources
    - 'src/Functions/Dump.php' # debug features
  dependency_paths:
    - 'vendor/'
