build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
checks:
  php: true
filter:
  excluded_paths:
    - 'tests/' # test suite
    - 'resources/' # other resources
    - 'src/Functions/Dump.php' # debug features
  dependency_paths:
    - 'vendor/'
