<?php
$path = '/admin/';
$frontend = $this->config->app->dir->public . $path . 'index.html';

// loading app
if (file_exists($frontend)) {

//    require_once $frontend;
    echo str_replace(
        ['href="./', 'src="./', 'href="assets/'],
        ['href="' . $path, 'src="' . $path, 'href="' . $path . 'assets/'],
        file_get_contents($frontend)
    );
}

// front-end not found
else {
    
    /** @var \Phalcon\Http\Response $response */
    $response = $this->response;
    $response->setStatusCode(404, 'Page not found');
    
    return $response;
}
