<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Zemit CMS Core Frontend Action View</h3>
            <p><?php echo 'Phalcon v' . (new \Phalcon\Support\Version)->get() . ' (#' . (new \Phalcon\Support\Version)->getId() . ')';?></p>
            <p><?php echo 'Zemit v' . (new \Zemit\Support\Version)->get() . ' (#' . (new \Zemit\Support\Version)->getId() . ')';?></p>
        </div>
    </div>
</div>

