<?php

declare(strict_types=1);

/**
 * This file is part of the Phalcon Kit.
 *
 * (c) Phalcon Kit Team
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

namespace PhalconKit\Mvc\Controller\Traits\Actions\Rest;

use Exception;
use Phalcon\Filter\Filter;
use Phalcon\Http\ResponseInterface;
use Phalcon\Mvc\ModelInterface;
use PhalconKit\Mvc\Controller\Traits\Abstracts\AbstractExpose;
use PhalconKit\Mvc\Controller\Traits\Abstracts\AbstractQuery;
use PhalconKit\Mvc\Controller\Traits\Abstracts\AbstractInjectable;
use PhalconKit\Mvc\Controller\Traits\Abstracts\AbstractParams;
use PhalconKit\Mvc\Controller\Traits\Abstracts\AbstractRestResponse;
use PhalconKit\Mvc\Model\Interfaces\PositionInterface;

trait ReorderAction
{
    use AbstractExpose;
    use AbstractQuery;
    use AbstractInjectable;
    use AbstractParams;
    use AbstractRestResponse;
    
    /**
     * Reorder the entity based on the provided position.
     *
     * @return ResponseInterface The response generated by the method.
     * @throws \Phalcon\Filter\Exception
     * @throws Exception
     */
    public function reorderAction(): ResponseInterface
    {
        $entity = $this->findFirst();
        
        if (!$entity) {
            return $this->setRestErrorResponse(404);
        }
        
        $position = $this->getParam('position', [Filter::FILTER_INT]);
        
        assert($entity instanceof PositionInterface);
        $reordered = $entity->reorder($position);
        
        $this->view->setVars([
            'reordered' => $reordered,
            'data' => $this->expose($entity),
            'messages' => $entity->getMessages(),
        ]);
        
        return $this->setRestResponse($reordered);
    }
}
